/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftSol from "./Nft.sol";
export type { nftSol };
import type * as nftFactorySol from "./NftFactory.sol";
export type { nftFactorySol };
export type { MarketplaceRegistry } from "./MarketplaceRegistry";
